import spotipy

from os import environ as env

scope = "playlist-modify-private,playlist-modify-public,playlist-read-private"
SPOTIFY_CLIENT_ID = env.get('SPOTIFY_CLIENT_ID')
SPOTIFY_CLIENT_SECRET = env.get('SPOTIFY_CLIENT_SECRET')


class Spotify:
    __PLAYLIST_NAME = "Billboard Time Machine"

    def __init__(self):
        self.__sp = spotipy.Spotify(
            auth_manager=spotipy.oauth2.SpotifyOAuth(SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET, "http://example.com",
                                                     scope=scope, open_browser=False))

    def get_playlist(self):
        playlists = self.__sp.current_user_playlists()
        for playlist in playlists['items']:
            if playlist['name'] == Spotify.__PLAYLIST_NAME:
                return playlist

        return self.__sp.user_playlist_create(self.__sp.current_user()['id'], Spotify.__PLAYLIST_NAME, False, False,
                                              "Generated by Robot")

    def get_song_ids(self, song_list):
        result = []
        for song in song_list:
            sp_song = self.__sp.search(" ".join(song).replace(" ", "+"), limit=1)
            found_items = sp_song['tracks']['items']
            if len(found_items) > 0:
                result.append(found_items[0]['id'])
        return result

    def fill_with_songs(self, playlist, song_ids):
        self.__sp.playlist_add_items(playlist['id'], song_ids, 0)
